### ISSUE TITLE
nifi-registry service never respond if via k8s port-forwarding

### ISSUE THREAD

**Issue by chwongeric** [dysnix/charts#111]
Dear dysnix/charts support team,

I was redirected from https://github.com/cetic/helm-nifi/issues/182 by cetic/helm-nifi support team, thinking this maybe related to chart maintained here.

All the detail of this issue has been listed in https://github.com/cetic/helm-nifi/issues/182, but I can capture all here:

Wish to seek help to overcome this strange issue accessing nifi-registry service via k8s port-forward. I had k8s cluster at remote so access all services UI via k8s port-forward. However, for accessing nifi-registry via k8s port-forward, no matter what local port I use, nifi-registry service seems never respond to request, but nifi service always works.

Why nifi service always works while nifi-registry service never regardless local port chosen? Is there any specifically additional tricks need to setup for nifi-registry in this helm-chart? Anything I might missed in value.yaml may caused this?

Here is my helm chart setup:
nifi:
helm:
`# https://github.com/cetic/helm-nifi/tree/0.7.8`
version: 0.7.8
image:
`# https://hub.docker.com/r/apache/nifi/tags`
tag: 1.13.0

value.yaml contains following to enable nifi-registry pod and service

> registry:
>   enabled: true
>   port: 80
>   url: "nifi-registry"

> % kubectl get svc  -n data-pipeline -o wide
> ...
> nifi                                 ClusterIP   100.70.32.121    <none>        8080/TCP,9929/TCP                                                                     25h    app=nifi,release=nifi
> nifi-headless                        ClusterIP   None             <none>        8080/TCP,6007/TCP                                                                     25h    app=nifi,release=nifi
> nifi-registry                        ClusterIP   100.71.235.65    <none>        80/TCP                                                                                25h    app.kubernetes.io/instance=nifi,app.kubernetes.io/name=registry

nifi-registry service (tcp port 80) works fine if access inside k8s cluster. However, if I try to access after k8s port-forward, it never respond.

-- from terminal A:

> %  kubectl port-forward sts/nifi-registry --namespace data-pipeline 20337:80
> Forwarding from 127.0.0.1:20337 -> 80
> Forwarding from [::1]:20337 -> 80
> Handling connection for 20337
> E1025 11:56:34.256702   10540 portforward.go:400] an error occurred forwarding 20337 -> 80: error forwarding port 80 to pod 559b96d74c2830f98345b7a4ea031153c5dc750175197e1e02d0f04626c57e43, uid : exit status 1: 2021/10/25 18:56:34 socat[2684522] E connect(5, AF=2 127.0.0.1:80, 16): Connection refused
> E1025 11:56:34.256719   10540 portforward.go:400] an error occurred forwarding 20337 -> 80: error forwarding port 80 to pod 559b96d74c2830f98345b7a4ea031153c5dc750175197e1e02d0f04626c57e43, uid : exit status 1: 2021/10/25 18:56:34 socat[2684523] E connect(5, AF=2 127.0.0.1:80, 16): Connection refused
> Handling connection for 20337

-- from terminal B:

> % curl -vv http://localhost:20337/nifi-registry/
> *   Trying ::1...
> * TCP_NODELAY set
> * Connected to localhost (::1) port 20337 (#0)
> > GET /nifi-registry/ HTTP/1.1
> > Host: localhost:20337
> > User-Agent: curl/7.64.1
> > Accept: */*
> > 
> * Empty reply from server
> 

However, if I port-forward to nifi (similarly to all other k8s service) via port-forward, it will respond request and access UI always works.

> % curl -vv http://localhost:20337/nifi          
> *   Trying ::1...
> * TCP_NODELAY set
> * Connected to localhost (::1) port 20337 (#0)
> > GET /nifi HTTP/1.1
> > Host: localhost:20337
> > User-Agent: curl/7.64.1
> > Accept: */*
> > 
> < HTTP/1.1 302 Found
> < Date: Mon, 25 Oct 2021 19:20:55 GMT
> < Location: http://localhost:20337/nifi/
> < Content-Length: 0
> < Server: Jetty(9.4.35.v20201120)

Thank you very much for your kind help!

**Comment by chwongeric** [comment]
After further investigation, I see nifi-registry-0 pod always serving in `nifi-registry-0:18080` instead of `0.0.0.0:18080` because immutable config file `conf/nifi-registry.properties` in container has this line: `nifi.registry.web.http.host=nifi-registry-0`

thus nifi-registry-0 can not accept from localhost:  so `http://nifi-registry-0:18080/nifi-registry` works but not `http://localhost:18080/nifi-registry`.  suspect this is the reason k8s port-forward always failed to reach nifi-registry.

Could you please share the tips to overwrite `conf/nifi-registry.properties` in this `https://github.com/cetic/helm-nifi/` chart which point to `https://github.com/dysnix/charts`  ?   Thank you very much!

>   condition: registry.enabled
>   name: nifi-registry
>   repository: https://dysnix.github.io/charts/
>   version: 0.3.2

> nifi@nifi-registry-0:/opt/nifi-registry$ tail -f ./nifi-registry-current/logs/nifi-registry-app.log
> ...
> 2021-10-22 05:19:53,856 INFO [main] org.eclipse.jetty.server.Server Started @16735ms
> 2021-10-22 05:19:53,857 INFO [main] o.apache.nifi.registry.jetty.JettyServer NiFi Registry has started. The UI is available at the following URLs:
> 2021-10-22 05:19:53,857 INFO [main] o.apache.nifi.registry.jetty.JettyServer http://nifi-registry-0:18080/nifi-registry				# <-- Note: not localhost or 0.0.0.0
> 2021-10-22 05:19:53,868 INFO [main] o.apache.nifi.registry.BootstrapListener Successfully initiated communication with Bootstrap
> 

> nifi@nifi-registry-0:/opt/nifi-registry/nifi-registry-current$  cat conf/nifi-registry.properties | grep http
> nifi.registry.web.http.host=nifi-registry-0
> nifi.registry.web.http.port=18080
> nifi.registry.web.https.host=
> nifi.registry.web.https.port=

> nifi@nifi-registry-0:/opt/nifi-registry/nifi-registry-current$ curl -v http://nifi-registry-0:18080/nifi-registry
> *   Trying 100.96.1.232...
> * TCP_NODELAY set
> * Expire in 200 ms for 4 (transfer 0x55da291e8f50)
> * Connected to nifi-registry-0 (100.96.1.232) port 18080 (#0)
> > GET /nifi-registry HTTP/1.1
> > Host: nifi-registry-0:18080
> > User-Agent: curl/7.64.0
> > Accept: */*
> > 
> < HTTP/1.1 302 Found
> < Date: Mon, 08 Nov 2021 01:33:21 GMT
> < Location: http://nifi-registry-0:18080/nifi-registry/
> < Content-Length: 0
> < Server: Jetty(9.4.19.v20190610)
> nifi@nifi-registry-0:/opt/nifi-registry/nifi-registry-current$ curl -v http://localhost:18080/nifi-registry
> *   Trying 127.0.0.1...
> * TCP_NODELAY set
> * Expire in 149999 ms for 3 (transfer 0x5582d17bff50)
> * Expire in 200 ms for 4 (transfer 0x5582d17bff50)
> * connect to 127.0.0.1 port 18080 failed: Connection refused
> *   Trying ::1...
> * TCP_NODELAY set
> * Expire in 149999 ms for 3 (transfer 0x5582d17bff50)
> * Immediate connect fail for ::1: Cannot assign requested address
> *   Trying ::1...
> * TCP_NODELAY set
> * Expire in 149999 ms for 3 (transfer 0x5582d17bff50)
> * Immediate connect fail for ::1: Cannot assign requested address
> * Failed to connect to localhost port 18080: Connection refused
> * Closing connection 0
> curl: (7) Failed to connect to localhost port 18080: Connection refused

**Comment by jirimedved** [comment]
Hello @chwongeric ,
use this

`# Additional environment variables to set
extraEnvs:
  - name: NIFI_REGISTRY_WEB_HTTP_HOST
    value: "0.0.0.0"`

**Comment by chwongeric** [comment]
@jirimedved , thank you very much for reply!  I think this tip should work than current relay approach via socat.

BTW, wondering if I can also ask for git `branch` support for nifi-registry's `values.yaml`?   I tried to add branch name like - `branch: 'develop'`  but no luck, all flow files always write to master branch instead.  How do I use specific branch with nifi-registry in `values.yaml`?  thanks a lot!

```
flowProvider:
  git:
    enabled: true
    url: 'https://user:passwd@bitbucket.org/developers/nifi_flows'
    remote: 'origin'
    branch: 'develop'
    user: 'user'
    password: 'passwd'
```

**Comment by chwongeric** [comment]
closing current issue and created another issue `https://github.com/dysnix/charts/issues/131`  for git branch
