### ISSUE TITLE
Registry authentication

### ISSUE THREAD

**Issue by bmgante** [dysnix/charts#123]
Hi,

Is this chart compatible with authentication for registry?
Can you provide some guidance on how to configure it in order to avoid having anonymous users?

**Comment by bmgante** [comment]
Noticed statefulset does not configure nothing related to authentication. I am using this as sub-chart for helm-nifi and it would be great if this could be improved to accept and implement the authentication mechanisms. Are there any plans to do so?

**Comment by pawankbh** [comment]
Any update on the above request

**Comment by wknickless** [comment]
@pawankbh I've just opened PR #199 to add authentication for nifi-registry.  Right now it only supports client certificate authentication.  Before I ask @dennybaa to merge it I want to also add OIDC authentication.

**Comment by wknickless** [comment]
@pawankbh @bmgante https://github.com/dysnix/charts/pull/199 is feature and test complete.  It would be great to get your feedback from whatever testing you can do.

**Comment by bmgante** [comment]
Great. I'll test it tomorrow and provide feedback.
