### ISSUE TITLE
Add License and README

### ISSUE THREAD

**Issue by a-nldisr** [dysnix/charts#20]
Hi, could you add a License and a README?

**Comment by a-nldisr** [comment]
@dennybaa

**Comment by dennybaa** [comment]
#25 
regarding readme not promising yet, though added the license

**Comment by a-nldisr** [comment]
Thank you

**Comment by a-nldisr** [comment]
Shall i leave this open now the license is added? Perhaps I have a few hours time in the next couple weeks to add a README inspired on bitnami or cetic where the default values are placed.

**Comment by dennybaa** [comment]
@a-nldisr Hello! Thanks for a proposal. This might be left open, since adding a good auto-generated readme for charts is a generally a good thing. I've tried a couple of solutions available, but haven't stick to any yet. Maybe you can suggest an option...

**Comment by a-nldisr** [comment]
Didnt even know it was a thing to be honest, but checked the repo's that I used before and found the bitnami-labs/readme-generator-for-helm. Dont know your requirements.
