### ISSUE TITLE
nifi-registry version 1.1.1 doesn't exist in the repo

### ISSUE THREAD

**Issue by shayki5** [dysnix/charts#213]
Hi, the latest nigi-registry version which available in the repo (https://dysnix.github.io/charts) is `1.1.0`.
I need version `1.1.1` in order to fix the `ingress` issue.
I can see the version in the releases page but not in the repo (also does'n exist [here](https://artifacthub.io/packages/helm/dysnix/nifi-registry)).
I think it because the action failed: https://github.com/dysnix/charts/actions/runs/2905447190/jobs/4624415687
Can you fix it please and deploy version `1.1.1`?
Thank you!

**Comment by daniel-yavorovich** [comment]
fixed, thank you!
