### ISSUE TITLE
Expose pritunl with ClusterIP instead of LoadBalancer

### ISSUE THREAD

**Issue by shotor** [dysnix/charts#31]
I see the pritunl service is fixed with LoadBalancer: https://github.com/dysnix/charts/blob/master/dysnix/pritunl/templates/service.yaml#L13

Any objections to allow this to be configurable?

I'm trying to expose it with ClusterIP and route using nginx-ingress-controller

**Comment by dennybaa** [comment]
@shotor Hey, well I don't think there's much sense in ClusterIP. Though having NodePort in addition to LoadBalancer is generally a good thing.

**Comment by shotor** [comment]
Yeah, you might be right. Still learning how to setup k8s.

I already have a LoadBalancer that I use together with nginx-ingress-controller. Now I have 2 load balancers. Probably need to set `loadBalancerIP` instead of ClusterIP.

**Comment by dennybaa** [comment]
@shotor Yeah, nginx ingress is used to load balance http/s traffic. While we need a loadbalancer which passes tcp/udp to pritunl openvpn or a nodeport. So far I'm going to close this. However you are welcome to open a PR.
