### ISSUE TITLE
index.yaml not updated

### ISSUE THREAD

**Issue by tunaman** [dysnix/charts#44]
Hi

Just noticed that chart-releaser uploaded the nifi-registry `0.3.2` release, but the index.yaml update was not triggered, see [the actions log](https://github.com/dysnix/charts/runs/2851535331?check_suite_focus=true ) and [the index.yaml](https://github.com/dysnix/charts/blob/gh-pages/index.yaml) is still showing the `0.3.1` release as the latest version. Is there still a manual action that needs to trigger the update for the index.yaml or is this a bug?

**Comment by dennybaa** [comment]
@tunaman Hey. Your issue's been resolved. But yeah there's been some strange behavior of the chart releaser action.
